name: Android CI

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup JDK 11 with caching
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          cache: gradle

      # Make Gradle wrapper executable
      - name: Make gradlew executable
        run: chmod +x ./ExpenseManager/gradlew

      # Build and test the app
      - name: Build and test
        working-directory: ./ExpenseManager
        run: ./gradlew build --no-daemon

      # Assemble debug APK
      - name: Assemble Debug APK
        working-directory: ./ExpenseManager
        run: ./gradlew assembleDebug --no-daemon

      # Assemble release APK
      - name: Assemble Release APK
        working-directory: ./ExpenseManager
        run: ./gradlew assembleRelease --no-daemon

      # Upload debug APK artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: Debug APK
          path: ExpenseManager/app/build/outputs/apk/debug/app-debug.apk

      # Upload release APK artifact
      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: Release APK
          path: ExpenseManager/app/build/outputs/apk/release/app-release.apk
